### ISSUE TITLE
Find a vector data example file that loads into QGIS as a cave

### ISSUE THREAD

**Issue by goatchurchprime** [CaveSurveying/tunnelx#11]
Following @ND84's comment here:  https://github.com/CaveSurveying/tunnelx/issues/10#issuecomment-536661639 I need an example file (shape file or other) that loads into QGIS and makes the kind of vectors, georeferencing, altitudes and labels information that we'd like to have output by tunnel.  

Tunnel already can output SVG, so has vector file output capability.  But I do not think there is such a thing a GeoSVG, and we lack and working example to base any future work on.  When we have an example, it will be possible to write the function in tunnel to emulate it.

**Comment by AndrewAkinson** [comment]
So here are some formats, I can get most of them to appear in QGIS, but they do not seem to have location information in them, and when I convert to a projected CRS they just disappear, so had no luck seeing them in 3D view

The original data is from here if people want to play

http://www.cave-registry.org.uk/svn/CheddarCatchment/Bagpit/


[Bagpit_otherformats.zip](https://github.com/CaveSurveying/tunnelx/files/3676101/Bagpit_otherformats.zip)


[BagpitP.pdf](https://github.com/CaveSurveying/tunnelx/files/3676079/BagpitP.pdf)
[BagpitE320.pdf](https://github.com/CaveSurveying/tunnelx/files/3676080/BagpitE320.pdf)
[Bagpit.pdf](https://github.com/CaveSurveying/tunnelx/files/3676089/Bagpit.pdf)


[_shapefiles.zip](https://github.com/CaveSurveying/tunnelx/files/3676096/_shapefiles.zip)

**Comment by patrickbwarren** [comment]
I made a fake cave survey which contains all the requested features and uploaded it to a sandbox repository here: https://github.com/CaveSurveying/sandbox
